import {dayKey,validVolume,totals,ensureDay,setGoal,progress} from './model.js';
import {emptyState,validateState,mergeBackup} from './data.js';
import {configured,getSession,initCloud,login,signup,resendConfirmation,recover,updatePassword,logout,observe,sync,adminStats,membership} from './cloud.js';
const source='https://www.nhs.uk/live-well/eat-well/food-guidelines-and-food-labels/water-drinks-nutrition/';
const facts=['Другие напитки тоже входят в общий объём жидкости за день.','Часть жидкости поступает с едой. Здесь мы записываем только напитки.','NHS советует пить регулярно в течение дня.','В жаркую погоду потребность в жидкости может увеличиваться.','При длительной физической активности жидкости может требоваться больше.','Вода — доступный и недорогой выбор напитка.','Чай и кофе тоже учитываются в дневном потреблении жидкости.','Молоко также входит в дневной объём жидкости; взрослым NHS предлагает варианты с меньшей жирностью.','NHS советует выбирать напитки с меньшим количеством сахара.','Общий ориентир — справочная величина. Индивидуальная потребность может отличаться.'];
const advice='Выберите удобный дневной ориентир. Для многих взрослых справочный ориентир — около 1,5–2 л жидкости из напитков в день. Чай и кофе тоже учитываются. Потребность индивидуальна; при жаре и длительной активности она может увеличиваться. Если врач назначил объём или ограничение жидкости, следуйте его рекомендации';
const app=document.querySelector('#app'),panel=document.querySelector('#panel');
let state={started:false,goal:1800,days:{}},tab='today',setup=false,storageError=false;
let ready=false,admin=false,cloudStatus='',needsPassword=false,registering=false;
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try { const saved=JSON.parse(localStorage.getItem('water-balance-v1')); if(saved && typeof saved.started==='boolean' && Number.isInteger(saved.goal) && saved.goal>=500 && saved.goal<=4000 && saved.days && typeof saved.days==='object') {state=saved; for(const [key,day] of Object.entries(state.days)){if(!day || !Array.isArray(day.entries)){delete state.days[key];continue;}day.entries=day.entries.filter(e=>e && validVolume(e.volume) && ['water','other'].includes(e.type) && Number.isFinite(e.time));if(!Number.isInteger(day.goal)||day.goal<500||day.goal>4000)delete day.goal;} } } catch {storageError=true;}
let current=ensureDay(state);let factIndex=firstFact();
function firstFact(){const d=new Date();return Math.floor(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())/86400000)%facts.length;}
function save(){try{if(configured){if(getSession())observe(state);}else localStorage.setItem('water-balance-v1',JSON.stringify(state));}catch{storageError=true;}}
const fmt=n=>n.toLocaleString('ru-RU');
const sourceLink=()=>`<a href="${source}" target="_blank" rel="noopener noreferrer">Источник: NHS ↗</a>`;
function goalForm(){return `<div class="goal-value"><span id="goal-number">${fmt(state.goal)}</span> <small>мл в день</small></div><input id="goal" aria-label="Дневная цель в миллилитрах" type="range" min="500" max="4000" step="100" value="${state.goal}"><div class="range-labels"><span>500 мл</span><span>4 000 мл</span></div><p id="glasses">${(state.goal/250).toLocaleString('ru-RU')} стакана по 250 мл</p><button class="primary" id="save-goal">Сохранить цель</button><p class="note">${advice}.</p>${sourceLink()}<p class="note">Для взрослых. Диапазон ползунка — настройка приложения, а не медицинская норма.</p>`;}
function render(){if(configured&&(!ready||!getSession()||needsPassword)){renderAuth();return;}current=ensureDay(state);save();app.innerHTML=`<header><div class="brand"><span class="logo">◒</span> Водный баланс</div><span class="eyebrow">ЛИЧНЫЙ ОРИЕНТИР</span></header>${storageError?'<p role="alert" class="warning">Хранилище браузера недоступно или повреждено. Сохранение данных может не работать.</p>':''}<p class="sync-status" id="sync-status" role="status">${escape(cloudStatus||'Локальное демо · облако ещё не подключено')}</p>`;
if(!state.started){app.innerHTML+=setup?`<section class="card"><span class="eyebrow">ШАГ 2 / 2</span><h1>Ваш дневной ориентир</h1>${goalForm()}</section>`:`<section class="welcome card"><span class="eyebrow">МАЛЕНЬКАЯ ПРИВЫЧКА КАЖДЫЙ ДЕНЬ</span>${drop(.35)}<h1>Ваш день.<br>Ваш водный баланс.</h1><p>Отмечайте напитки и следите за своим дневным ориентиром в удобном ритме.</p><button id="start" class="primary">Начать →</button><p class="note">${configured?'Личный дневник для взрослых':'Учебное демо для взрослых · без регистрации'}</p></section>`;bind();return;}
app.innerHTML+=`<nav aria-label="Разделы">${[['today','Сегодня'],['history','История'],['settings','Настройки']].map(([id,name])=>`<button data-tab="${id}" class="${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}>${name}</button>`).join('')}</nav>`;
if(tab==='settings')app.innerHTML+=`<section class="card"><span class="eyebrow">ВАШ РИТМ</span><h1>Дневная цель</h1>${goalForm()}<p class="note">Новая цель применяется к сегодняшнему и будущим дням. Цели прошлых дней сохраняются.</p></section><section class="card account"><h2>Данные и доступ</h2><p class="note">${configured?'Для оценки приложения администратор видит активное время, количество записей, дни использования и повторные заходы. Содержимое дневника доступно только вам.':'Локальное демо: записи остаются в этом браузере. Вход по приглашению станет доступен после подключения Supabase.'}</p><button id="export" class="secondary">Скачать резервную копию</button><label class="secondary file-label">Восстановить из файла<input id="import" type="file" accept="application/json,.json"></label><p class="note">Восстановление добавляет отсутствующие записи. Существующие записи и цели сохраняются. Файл содержит ваш дневник — храните его в безопасном месте.</p>${configured?'<button id="sync" class="secondary">Синхронизировать</button><button id="logout" class="secondary">Выйти и убрать данные с устройства</button>':'<button id="cloud-info" class="secondary">Вход по приглашению</button>'}${admin?'<button id="stats" class="secondary">Статистика участников</button>':''}<p id="account-error" role="alert" class="warning"></p></section>`;
else if(tab==='history')renderHistory();else renderToday();bind();bindAccount();}
function drop(fill){return `<svg class="drop" viewBox="0 0 200 240" aria-hidden="true"><defs><clipPath id="drop-clip"><path d="M100 12 C80 52 25 105 25 155 A75 75 0 0 0 175 155 C175 105 120 52 100 12Z"/></clipPath><linearGradient id="water" x2="1" y2="1"><stop stop-color="#27cbd3"/><stop offset="1" stop-color="#3777ee"/></linearGradient></defs><path d="M100 12 C80 52 25 105 25 155 A75 75 0 0 0 175 155 C175 105 120 52 100 12Z" fill="#e8f3fb" stroke="#d0e5f3" stroke-width="2"/><g clip-path="url(#drop-clip)"><rect class="water-fill" x="0" y="${230-218*fill}" width="200" height="240" fill="url(#water)"/></g><path d="M55 148 Q53 176 68 191" fill="none" stroke="white" stroke-width="8" stroke-linecap="round" opacity=".65"/></svg>`;}
function renderToday(){const day=state.days[current],{total,water}=totals(day.entries),p=progress(total,day.goal);app.innerHTML+=`<div class="title-row"><div><p class="date">${new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long',weekday:'long'})}</p><h1>Сегодня в балансе</h1></div><button id="fact" class="info" aria-label="А вы знали?">?</button></div><section class="card hero"><span class="eyebrow">ВЫПИТО ЗА СЕГОДНЯ</span><div class="big">${fmt(total)} <small>мл</small></div><p class="muted">из ${fmt(day.goal)} мл</p><div class="drop-wrap">${drop(p.fill)}<span class="percentage">${p.percent}%</span></div><p class="status" aria-live="polite">${p.remaining?`Осталось ${fmt(p.remaining)} мл`:'Цель на сегодня достигнута'}</p><div class="water-stat"><span>◌ Чистая вода</span><strong>${fmt(water)} мл</strong></div><button id="add" class="primary">＋ Добавить напиток</button></section><section class="entries"><div class="title-row"><h2>Напитки сегодня</h2><span class="muted">${day.entries.length} записей</span></div>${day.entries.length?day.entries.slice().reverse().map(e=>`<div class="entry"><span class="drink-icon">${e.type==='water'?'◒':'☕'}</span><div><strong>${e.type==='water'?'Вода':'Другой напиток'}</strong><small>${new Date(e.time).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div><b>${fmt(e.volume)} мл</b><button data-delete="${e.id}" class="delete" aria-label="Удалить запись ${e.volume} мл">×</button></div>`).join(''):'<div class="empty">Здесь пока тихо.<br><span>Добавьте первый напиток — он появится в списке.</span></div>'}</section>`;}
function renderHistory(){const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return {date:d,key:dayKey(d),data:state.days[dayKey(d)]};});const max=Math.max(1,...days.map(d=>Math.max(d.data?.goal||0,totals(d.data?.entries||[]).total)));app.innerHTML+=`<section class="card"><span class="eyebrow">ПОСЛЕДНИЕ 7 ДНЕЙ</span><h1>Ваш ритм</h1><p class="muted">Бирюзовый — выпито · черта — цель</p><div class="chart">${days.map(d=>{const total=totals(d.data?.entries||[]).total;return `<div class="column"><span>${d.data?fmt(total):'—'}</span><div class="bar-track"><div class="bar" style="height:${total/max*100}%"></div>${d.data?.goal?`<i style="bottom:${d.data.goal/max*100}%"></i>`:''}</div><small>${d.date.toLocaleDateString('ru-RU',{day:'numeric',month:'numeric'})}</small></div>`;}).join('')}</div><div class="history-list">${days.slice().reverse().map(d=>`<div><span>${d.key===current?'Сегодня':d.date.toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}</span><strong>${d.data?fmt(totals(d.data.entries).total)+' мл':'Нет записей'}</strong><small>Цель: ${d.data?.goal?fmt(d.data.goal)+' мл':'не сохранена'}</small></div>`).join('')}</div><p class="note">В дни без сохранённых данных цель не отображается.</p></section>`;}
function bind(){document.querySelector('#start')?.addEventListener('click',()=>{setup=true;render();});document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});const slider=document.querySelector('#goal');if(slider){slider.oninput=()=>{document.querySelector('#goal-number').textContent=fmt(+slider.value);document.querySelector('#glasses').textContent=`${(+slider.value/250).toLocaleString('ru-RU')} стакана по 250 мл`;};document.querySelector('#save-goal').onclick=()=>{setGoal(state,+slider.value);tab='today';render();};}document.querySelector('#add')?.addEventListener('click',addPanel);document.querySelector('#fact')?.addEventListener('click',factPanel);document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{state.days[current].entries=state.days[current].entries.filter(e=>e.id!==b.dataset.delete);render();});}
function openPanel(html){panel.innerHTML=`<button class="close" aria-label="Закрыть">×</button>${html}`;panel.querySelector('.close').onclick=()=>panel.close();panel.showModal();}
function addPanel(){openPanel(`<span class="eyebrow">НОВАЯ ЗАПИСЬ</span><h2>Добавить напиток</h2><form id="drink-form"><fieldset><legend>Тип напитка</legend><label><input type="radio" name="type" value="water" checked> Вода</label><label><input type="radio" name="type" value="other"> Другой напиток</label></fieldset><div class="presets">${[150,250,500].map(v=>`<button type="button" data-volume="${v}">${v} мл</button>`).join('')}</div><label class="volume-label" for="volume">Свой объём, мл</label><input id="volume" type="number" inputmode="numeric" min="1" max="2000" step="1" value="250" required><p class="note">От 1 до 2 000 мл на запись — ограничение ввода.</p><p id="error" role="alert"></p><button class="primary">Добавить</button></form>`);panel.querySelectorAll('[data-volume]').forEach(b=>b.onclick=()=>panel.querySelector('#volume').value=b.dataset.volume);panel.querySelector('form').onsubmit=e=>{e.preventDefault();const value=panel.querySelector('#volume').value;if(!validVolume(value)){panel.querySelector('#error').textContent='Введите целое число от 1 до 2 000 мл.';return;}current=ensureDay(state);state.days[current].entries.push({id:crypto.randomUUID(),type:new FormData(e.target).get('type'),volume:+value,time:Date.now()});panel.close();render();};}
function factPanel(){openPanel(`<span class="eyebrow">А ВЫ ЗНАЛИ?</span><h2>О напитках и воде</h2><p class="fact-text">${facts[factIndex]}</p>${sourceLink()}<button id="next-fact" class="primary">Ещё факт →</button>`);panel.querySelector('#next-fact').onclick=()=>{factIndex=(factIndex+1)%facts.length;panel.close();factPanel();};}
function checkDate(){if(dayKey()!==current){current=ensureDay(state);factIndex=firstFact();render();}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkDate();});window.addEventListener('focus',checkDate);setInterval(checkDate,30000);
function report(message){cloudStatus=message;const node=document.querySelector('#sync-status');if(node)node.textContent=message;}
function renderAuth(){app.innerHTML=`<header><div class="brand">◒ Водный баланс</div></header><section class="card"><span class="eyebrow">ЛИЧНЫЙ АККАУНТ</span><h1>${needsPassword?'Установите пароль':registering?'Создать аккаунт':'Ваш личный дневник'}</h1>${!ready?'<p>Загрузка…</p>':`<form id="auth-form">${needsPassword?'':'<label for="email">Почта</label><input id="email" type="email" autocomplete="username" required>'}<label for="password">Пароль</label><input id="password" type="password" autocomplete="${needsPassword||registering?'new-password':'current-password'}" minlength="8" required><button class="primary">${needsPassword?'Сохранить пароль':registering?'Зарегистрироваться':'Войти'}</button></form>${needsPassword?'':`<button id="auth-mode" class="secondary">${registering?'Уже есть аккаунт — войти':'Создать аккаунт'}</button><button id="resend-confirmation" class="secondary">Отправить подтверждение повторно</button>${registering?'<p class="note">После регистрации подтвердите почту по ссылке из письма. До подтверждения вход закрыт.</p>':'<button id="recover" class="secondary">Восстановить пароль</button>'}`}`}<p class="note">Для оценки приложения собираются активное время, количество записей, дни использования и повторные заходы. Администратор видит эту статистику. Ваш дневник доступен только вам.</p><p id="auth-error" class="warning" role="alert">${escape(cloudStatus)}</p></section>`;
 const form=document.querySelector('#auth-form');if(form)form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;try{if(registering&&!needsPassword){await signup(document.querySelector('#email').value.trim(),document.querySelector('#password').value);document.querySelector('#auth-error').textContent='Если адрес доступен для регистрации, придёт письмо подтверждения. Проверьте также папку «Спам». Откройте ссылку из письма, затем войдите. Если письма нет, попробуйте отправить подтверждение повторно.';document.querySelector('#password').value='';button.disabled=false;return;}if(needsPassword){await updatePassword(document.querySelector('#password').value);needsPassword=false;}else{state=await login(document.querySelector('#email').value,document.querySelector('#password').value);}cloudStatus='Сохранено на устройстве';render();void sync();try{admin=await membership();render();}catch(error){report(error.message);}}catch(error){document.querySelector('#auth-error').textContent=error.message;button.disabled=false;}};
 document.querySelector('#auth-mode')?.addEventListener('click',()=>{registering=!registering;cloudStatus='';renderAuth();});
 document.querySelector('#resend-confirmation')?.addEventListener('click',async e=>{const email=document.querySelector('#email');if(!email.reportValidity())return;e.target.disabled=true;try{await resendConfirmation(email.value.trim());document.querySelector('#auth-error').textContent='Если подтверждение требуется, письмо будет отправлено. Проверьте почту и папку «Спам».';}catch(error){document.querySelector('#auth-error').textContent=error.message;}finally{e.target.disabled=false;}});
 document.querySelector('#recover')?.addEventListener('click',async()=>{const email=document.querySelector('#email');if(!email.reportValidity())return;try{await recover(email.value);document.querySelector('#auth-error').textContent='Если адрес зарегистрирован, на него придёт письмо для восстановления.';}catch(error){document.querySelector('#auth-error').textContent=error.message;}});
}
function bindAccount(){const error=message=>{document.querySelector('#account-error').textContent=message;};document.querySelector('#export')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`water-balance-${dayKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 document.querySelector('#import')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('Максимальный размер файла — 5 МБ.');const backup=JSON.parse(await file.text());if(backup.version!==1)throw Error('Неподдерживаемая версия копии.');const clean=validateState(backup.state);openPanel(`<h2>Восстановить историю?</h2><p>Дней в копии: ${Object.keys(clean.days).length}. Отсутствующие записи будут добавлены в текущий дневник.</p><button id="confirm-import" class="primary">Добавить записи из копии</button>`);document.querySelector('#confirm-import').onclick=()=>{state=mergeBackup(state,clean);panel.close();render();};}catch(err){error(err.message);}e.target.value='';});
 document.querySelector('#cloud-info')?.addEventListener('click',()=>openPanel('<h2>Облако ещё не подключено</h2><p>После создания проекта Supabase появятся вход по приглашению, синхронизация и статистика участников. Сейчас доступно локальное демо.</p>'));
 document.querySelector('#sync')?.addEventListener('click',()=>void sync());document.querySelector('#logout')?.addEventListener('click',async()=>{try{await logout();state=emptyState();admin=false;render();}catch(err){error(err.message);}});
 document.querySelector('#stats')?.addEventListener('click',async()=>{try{const rows=await adminStats();openPanel(`<h2>Статистика участников</h2><p class="note">Время — видимая вкладка в фокусе. Это приблизительная оценка, а не доказательство внимания. Возвращения — повторные открытия приложения.</p>${rows.length?rows.map(row=>`<article class="usage"><strong>${escape(row.label)}</strong><p>Активное время: ${fmt(row.active_seconds)} с<br>Открытий: ${fmt(row.visits)}<br>Дней активности: ${row.active_days}<br>Записей добавлено: ${row.entries_added}<br>Последняя активность: ${row.last_seen?escape(new Date(row.last_seen).toLocaleString('ru-RU')):'пока нет'}</p></article>`).join(''):'<p>Активности пока нет.</p>'}`);}catch(err){error(err.message);}});
}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>report('Офлайн-загрузка недоступна. Открывайте приложение с интернетом.'));
try{const result=await initCloud(value=>{state=value;if(tab!=='settings'&&!panel.open&&!needsPassword)render();},report);if(result){state=result.state;needsPassword=result.passwordRequired;}ready=true;render();if(result&&!needsPassword){void sync();membership().then(value=>{admin=value;render();}).catch(error=>report(error.message));}}catch(error){ready=true;state=emptyState();report(error.message);render();}

