import assert from 'node:assert/strict';
import {dayKey,ensureDay,setGoal,totals,progress,validVolume} from './model.js';
import {emptyState,validateState,diffStates,applyOps,mergeBackup} from './data.js';
const a=new Date(2026,9,4,23,59),b=new Date(2026,9,5,0,1),state={started:false,goal:1800,days:{}};
assert.equal(ensureDay(state,a),'2026-10-04');assert.equal(Object.keys(state.days).length,0);
setGoal(state,1800,a);const day=state.days[dayKey(a)];day.entries.push({type:'water',volume:500},{type:'other',volume:2000});
assert.deepEqual(totals(day.entries),{total:2500,water:500});assert.deepEqual(progress(2500,1800),{percent:139,fill:1,remaining:0});
day.entries.splice(1,1);assert.equal(totals(day.entries).total,500);
ensureDay(state,b);setGoal(state,2000,b);assert.equal(day.goal,1800);assert.equal(state.days[dayKey(b)].goal,2000);assert.equal(totals(state.days[dayKey(b)].entries).total,0);
const restored=JSON.parse(JSON.stringify(state));assert.deepEqual(restored,state);
for(const v of ['0','-1','1.5','2001','','NaN'])assert.equal(validVolume(v),false);for(const v of ['1','250','2000'])assert.equal(validVolume(v),true);
console.log('Проверки логики пройдены: запуск, напитки, удаление, превышение, цели, сериализация, смена дня, ввод.');
const initial=emptyState(),changed=emptyState();setGoal(changed,1800,a);changed.days[dayKey(a)].entries.push({id:'entry-one',type:'other',volume:250,time:a.getTime()});
const ops=diffStates(initial,changed);assert.deepEqual(applyOps(initial,ops),changed);assert.deepEqual(applyOps(applyOps(initial,ops),ops),changed);
const deviceB=structuredClone(changed);deviceB.days[dayKey(a)].entries.push({id:'entry-two',type:'water',volume:150,time:a.getTime()});
const deviceA=structuredClone(changed);deviceA.days[dayKey(a)].entries=[];
const merged=applyOps(applyOps(changed,diffStates(changed,deviceB)),diffStates(changed,deviceA));assert.deepEqual(merged.days[dayKey(a)].entries.map(e=>e.id),['entry-two']);
assert.deepEqual(validateState(changed),changed);assert.deepEqual(mergeBackup(changed,changed),changed);assert.equal(mergeBackup(deviceB,changed).days[dayKey(a)].entries.length,2);
const evil=structuredClone(changed);evil.days[dayKey(a)].entries[0].id='"><script>';assert.throws(()=>validateState(evil));
const invalid=structuredClone(changed);invalid.days['2026-02-31']={entries:[]};assert.throws(()=>validateState(invalid));
const badVolume=structuredClone(changed);badVolume.days[dayKey(a)].entries[0].volume=0;assert.throws(()=>validateState(badVolume));
console.log('Проверки очереди и копий пройдены: повторная отправка, параллельное добавление/удаление, восстановление без дублей, отклонение повреждённых файлов.');
